### PR TITLE
Add README.rst and rename notebooks to establish ordering

### PR DESCRIPTION
**Pull request by taldcroft**
This patch is actually reviewable so I'm putting it as a PR.

### CODE REVIEW

**Comment by astrofrog** [comment]
:+1:

**Comment by taldcroft** [comment]
@astrofrog - I was _hoping_ it would just work, but apparently changing the file names has broken the HTML links.

**Comment by taldcroft** [comment]
Try clicking on the notebook links in http://astropy4scipy2014.readthedocs.org/

**Comment by astrofrog** [comment]
Ah yes you have to re-generate the HTML files and commit them (or alternatively, rename the HTML files). To re-generate the HTML, you type `make` inside `notebooks`.

**Comment by embray** [comment]
No, it's not just regenerating the HTML files.  The links in the notebooks from #8 actually need to be updated now.

**Comment by embray** [comment]
I will fix the links.

**Comment by taldcroft** [comment]
I just merged #10 that I think fixes everything.  But please look and make sure I did it right!

**Comment by embray** [comment]
The links _in_ the notebooks to the raw notebook files are still broken, since they refer to the old name of the files.

**Comment by taldcroft** [comment]
Got it,  I missed those.  Previously the HTML versions were entirely missing.

**Pull request merged**
